Django_part_5/first_project/basicapp/urls.py
from django.urls import path
from basicapp import  views

app_name='basicapp'
urlpatterns = [
path('register/', views.register, name="register" ),
path('user_login', views.user_login, name="user_login" ),
]

Django_part_5/first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from basicapp import views
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
    path('logout/', views.user_logout, name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_part_5/first_project/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_pic = models.ImageField(upload_to='profile_pics', blank = True)
    portfolio_site = models.URLField(blank=True)

    def __str__(self):
        return self.user.username


# Create your models here.

Django_part_5/first_project/basicapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields=('username','email','password')

class UserProfileInfoForm(ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('profile_pic', 'portfolio_site')

Django_part_5/first_project/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'basicapp/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            # if 'profile_pic' in request.FILES:
            #     profile.profile_pic = request.FILES['profile_pic']

            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form=UserForm()
        profile_form= UserProfileInfoForm()

    return render(request, 'basicapp/registration.html',
    { 'user_form':user_form,
      'profile_form':profile_form,
      'registered':registered
    })

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'basicapp/login.html', {})

Django_part_5/first_project/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a></li>
          {% else %}
            <li> <a class="navbar-link" href="{% url 'basicapp:user_login' %}">LOGIN</a> </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

Django_part_5/first_project/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to index page</h1>

</div>
{% endblock %}

Django_part_5/first_project/templates/basicapp/login.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form  action="{% url 'basicapp:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">Username</label>
    <input type="text" name="username" value="" placeholder="Username">

    <label for="password">Enter Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>
{% endblock %}

Django_part_5/first_project/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to registration page</h1>
  {% if registered %}
    <h3>Thanks for registering</h3>
  {%else %}
    <h3>Fill the Form</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Submit">

    </form>
  {% endif %}

</div>
{% endblock %}